const baseUrl = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons';

export const languageLogoMapping: Record<string, string> = {
  TypeScript: `${baseUrl}/typescript/typescript-original.svg`,
  JavaScript: `${baseUrl}/javascript/javascript-original.svg`,
  Ruby: `${baseUrl}/ruby/ruby-original.svg`,
  Python: `${baseUrl}/python/python-original.svg`,
  PHP: `${baseUrl}/php/php-original.svg`,
  Java: `${baseUrl}/java/java-original.svg`,
  Go: `${baseUrl}/go/go-original.svg`,
  'C#': `${baseUrl}/csharp/csharp-original.svg`,
  'C++': `${baseUrl}/cplusplus/cplusplus-original.svg`,
  C: `${baseUrl}/c/c-original.svg`,
  Swift: `${baseUrl}/swift/swift-original.svg`,
  CSS: `${baseUrl}/css3/css3-original.svg`,
  HTML: `${baseUrl}/html5/html5-original.svg`,
  Dockerfile: `${baseUrl}/docker/docker-original.svg`,
  Lua: `${baseUrl}/lua/lua-original.svg`,
  CoffeeScript: `${baseUrl}/coffeescript/coffeescript-original.svg`,
  'Vim Snippet': `${baseUrl}/vim/vim-original.svg`,
  'Vim script': `${baseUrl}/vim/vim-original.svg`,
  HaXe: `${baseUrl}/haxe/haxe-original.svg`,
  Dart: `${baseUrl}/dart/dart-original.svg`,
  R: `${baseUrl}/r/r-original.svg`,
  Rust: `${baseUrl}/rust/rust-plain.svg`,
  'Objective-C': `${baseUrl}/objectivec/objectivec-plain.svg`,
  Crystal: `${baseUrl}/crystal/crystal-original.svg`,
  Scala: `${baseUrl}/scala/scala-original.svg`,
  Groovy: `${baseUrl}/groovy/groovy-original.svg`,
  Kotlin: `${baseUrl}/kotlin/kotlin-original.svg`,
  Haskell: `${baseUrl}/haskell/haskell-original.svg`,
  Matlab: `${baseUrl}/matlab/matlab-original.svg`,
  Elixir: `${baseUrl}/elixir/elixir-original.svg`,
};
